// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPak0gPJeWtg4U9JPOyBlP2plSw-A4yCo',
    appId: '1:761243247606:web:379bd9438d8cbca51a9dd7',
    messagingSenderId: '761243247606',
    projectId: 'docapointment-1a16e',
    authDomain: 'docapointment-1a16e.firebaseapp.com',
    storageBucket: 'docapointment-1a16e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByb1KisJchrA_lIU_EtUUmqIuJT83fCQw',
    appId: '1:761243247606:android:fa72f9a686a821651a9dd7',
    messagingSenderId: '761243247606',
    projectId: 'docapointment-1a16e',
    storageBucket: 'docapointment-1a16e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvg8JfK7Yt0DQtUGmh33GPEQLoPGywrQY',
    appId: '1:761243247606:ios:db10bbaf0aeda5b51a9dd7',
    messagingSenderId: '761243247606',
    projectId: 'docapointment-1a16e',
    storageBucket: 'docapointment-1a16e.appspot.com',
    iosBundleId: 'com.example.doctorconsultant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvg8JfK7Yt0DQtUGmh33GPEQLoPGywrQY',
    appId: '1:761243247606:ios:e1cf162ae0f326241a9dd7',
    messagingSenderId: '761243247606',
    projectId: 'docapointment-1a16e',
    storageBucket: 'docapointment-1a16e.appspot.com',
    iosBundleId: 'com.example.doctorconsultant.RunnerTests',
  );
}
